#!/bin/sh
#
#	MOTD for Raspian
#
#	This was tested on model 3B+
#
#	for better understanding visit: 
#	https://ownyourbits.com/2017/04/05/customize-your-motd-login-message-in-debian-and-ubuntu/
#
#	File Location
#	/etc/update-motd.d/
#
#	GitHub repository:
#	https://github.com/MrCaringi/motd.git 
#
#	For Weather API locations:
#	https://pastebin.com/dbtemx5F
#
#	Packages required:
#	figlet	lolcat	curl	cut
#
#	Gracias Pablo, eres un sol
#
#############################
#
#	Last Modified
#		2020-03-28	wttr.in implementation
#

upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
secs=$((${upSeconds}%60))
mins=$((${upSeconds}/60%60))
hours=$((${upSeconds}/3600%24))
days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"`
#	Variables nuevas
temp="$(/opt/vc/bin/vcgencmd measure_temp | cut -d "=" -f 2)"
temp="$(echo $temp | cut -c 1-4)"
host="$(cat /etc/hostname)"
#	Ruta de archivos de Temp Promedio
ruta=/home/pi/scripts/
m5=$(echo $ruta"m5")
m10=$(echo $ruta"m10")
m60=$(echo $ruta"m60")
m480=$(echo $ruta"m480")
average_temp=$(echo "1m $temp / 5m `cat $m5 | cut -c 1-4` / 10m `cat $m10 | cut -c 1-4` / 1h `cat $m60 | cut -c 1-4` / 8h `cat $m480 | cut -c 1-4`")
# get the load averages
read one five fifteen rest < /proc/loadavg

##	Publicar el host name
##	comentar la version de "lolcat" si no es compatible con el terminal
#figlet $host | lolcat
figlet "            $host"

#Clima
curl -s wttr.in/mty?1?q?n | tail -n 12 | head -n 10

echo "$(tput setaf 3)
`date +"%A, %e %B %Y, %r"`
`uname -srmo`$(tput setaf 4)

Uptime.............: ${UPTIME}
Average Temp (°C)..: `echo $average_temp`
Memory.............: `cat /proc/meminfo | grep MemFree | awk {'print $2'}`kB (Free) / `cat /proc/meminfo | grep MemTotal | awk {'print $2'}`kB (Total)
Load Averages......: ${one}, ${five}, ${fifteen} (1, 5, 15 min)
Running Processes..: `ps ax | wc -l | tr -d " "`
IP Addresses.......: `ip a | grep glo | awk '{print $2}' | head -1 | cut -f1 -d/`
<>
$(tput sgr0)"
