#!/bin/sh
#
#	MOTD for Raspian
#
#	This was tested on model 3B+
#
#	for better understanding visit: 
#	https://ownyourbits.com/2017/04/05/customize-your-motd-login-message-in-debian-and-ubuntu/
#
#	GitHub repository:
#	https://github.com/MrCaringi/motd.git 
#
#	For Weather API locations:
#	https://pastebin.com/dbtemx5F
#
#	Packages required:
#	figlet	lolcat	curl	cut
#
#	Gracias Pablo, eres un sol
#

upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
secs=$((${upSeconds}%60))
mins=$((${upSeconds}/60%60))
hours=$((${upSeconds}/3600%24))
days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"`
#	Variables nuevas
temp="$(/opt/vc/bin/vcgencmd measure_temp | cut -d "=" -f 2)"
host="$(cat /etc/hostname)"

# get the load averages
read one five fifteen rest < /proc/loadavg
#	Primero, lo primero: el Hostname
figlet $host | lolcat 
echo "$(tput setaf 3)
`date +"%A, %e %B %Y, %r"`
`uname -srmo`$(tput setaf 4)

Uptime.............: ${UPTIME}
Temp...............: `echo $temp`
Memory.............: `cat /proc/meminfo | grep MemFree | awk {'print $2'}`kB (Free) / `cat /proc/meminfo | grep MemTotal | awk {'print $2'}`kB (Total)
Load Averages......: ${one}, ${five}, ${fifteen} (1, 5, 15 min)
Running Processes..: `ps ax | wc -l | tr -d " "`
IP Addresses.......: `ip a | grep glo | awk '{print $2}' | head -1 | cut -f1 -d/`

Weather............: `curl -s "http://rss.accuweather.com/rss/liveweather_rss.asp?metric=1&locCode=NAM|MX|MX005|MONTERREY|" | sed -n '/Currently:/ s/.*: \(.*\): \([0-9]*\)\([CF]\).*/\2°\3, \1/p'`

$(tput sgr0)"
